app/urls.py
from django.urls import path
from . import views

app_name = "app"
urlpatterns = [
  path("", views.index, name="index"),
  path("store/", views.store, name="store"),
  path("orders/", views.orders, name="orders"),
  path("pay/<int:item_id>/<str:currency>/", views.make_payment, name="pay"),
  path("paid/", views.verify_payment, name="paid"),
]

spacyd/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('app.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("register/", views.register_request, name="register"),
    path("login/", views.login_request, name="login"),
    path("logout/", views.logout_request, name="logout"),
]

store/models.py
from locale import currency
from django.db import models

class Item(models.Model):
  """
  Model for item details
  """
  name = models.CharField(max_length=100)
  description = models.CharField(max_length=1000)
  
  def __str__(self) -> str:
    return self.name

class Price(models.Model):
  """
  Model for item price
  """
  item = models.ForeignKey(Item, on_delete=models.CASCADE)
  #currency = models.TextChoices('USD', 'SGD')
  currency = models.CharField(max_length=3)
  amount = models.IntegerField()
  
  def __str__(self) -> str:
    return f"{self.item}: {self.amount} {self.currency}"

class Purchase(models.Model):
  """
  Model for purchases made (aka fulfilled orders)
  """
  receipt_id = models.CharField(max_length=12)
  item = models.ForeignKey(Item, on_delete=models.CASCADE)
  currency = models.CharField(max_length=3)
  amount = models.IntegerField()
  to_balance = models.IntegerField()
  user_id = models.CharField(max_length=50)
  timestamp = models.DateTimeField()

store/views.py
from django.http import JsonResponse
from django.shortcuts import render
from .models import Item, Price, Purchase

def get_items(request, currency):
  """
  Get all items in store and price with the specified currency.
  """
  prices = Price.objects.filter(currency=currency)
  items = prices.values('id', 'amount', 'currency', 'item__id', 'item__name', 'item__description')
  items = [{
    'id': x['item__id'],
    'price': x['amount'],
    'currency': x['currency'],
    'name': x['item__name'],
    'description': x['item__description']
  } for x in items]
  return JsonResponse({"data": items})

def get_item(request, item_id, currency):
  """
  Get item with provided id and currency (to know price)
  """
  price = Price.objects.get(item__id=item_id, currency=currency)
  item = {
    'id': price.item.id,
    'price': price.amount,
    'currency': price.currency,
    'name': price.item.name,
    'description': price.item.description
  }
  return JsonResponse({'data': item})

def get_orders(request, user_id):
  """
  Get purchases made by user_id
  """
  purchase = Purchase.objects.filter(user_id=user_id)
  orders = [{
    "name": x.item.name,
    "description": x.item.description,
    "currency": x.currency,
    "amount": x.amount,
    "timestamp": x.timestamp,
  } for x in purchase]
  return JsonResponse({"data": orders})

def save_purchase(request):
  """
  Save a verified purchase
  """
  data = request.POST
  purchase = Purchase(**data)
  purchase.save()
  return JsonResponse({"data": {"success": True}})

app/templates/app/base.html
{% load static %}

<html>
  <head>
    <link rel="stylesheet" type="text/css" href="{% static 'app/style.css' %}">
  </head>
  <body>
    <div id="navbar">
      {% block navbar %}
        <nav class="navbar">
          {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
            {{user.username}}
          {% else %}
            <a class="nav-link" href="{% url 'users:login' %}">Login</a>
            |
            <a class="nav-link" href="{% url 'users:register' %}">Register</a> 
          {% endif %}
        </nav>
      {% endblock navbar %}  
    </div>
    <div id="messages">
      {% block messages %}
      {% if messages %}
        <ul class="messages">
          {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
        </ul>
      {% endif %}
      {% endblock messages %}
    </div>
    <div id="content">
      {% block content %}
      {% endblock content %}
    </div>
  </body>
</html>

app/templates/app/index.html
{% extends 'app/base.html' %}
{% block content %}
<div class="home">
  <p>Go to</p>
  <p>
    <a href="{% url 'app:store' %}">store</a>
  </p>
  <p>or view</p>
  <p><a href="{% url 'app:orders' %}">orders</a></p>
</div>
{% endblock content %}

app/templates/app/orders.html
{% extends 'app/base.html' %}
{% load humanize %}
{% block content %}
<h1>Orders</h1>
<div>
  <dl>
    {% for order in orders %}
      <dt>
        <big>{{order.name}}</big>
        - {{order.amount | intcomma}} {{order.currency}}
      </dt>
      <dd>
        {{order.timestamp}} - {{order.description}}
      </dd>
    {% endfor %}
  </dl>
</div>
<p>
  Go to 
  <a href="{% url 'app:store' %}">store</a>
</p>
{% endblock content %}

app/templates/app/pay.html
{% extends 'app/base.html' %}
{% load humanize %}
{% block content %}
<div>
  <h2>Accepting payment for {{item.name}}</h2>
  <h3>Send {{item.price | intcomma}} {{item.currency}} and click on Payment made</h3>
  <h4>{{account.type}}: {{account.id}}</h4>
  <h4>Bank: {{account.bank}}</h4>
  <h4>Number: {{account.number}}</h4>
  <h4>Name: {{account.name}}</h4>
</div>
<div>
  <form action="{% url 'app:paid'%}" method="POST">
    {% csrf_token %}
    <input type="hidden" name="currency" value={{item.currency}}>
    <input type="hidden" name="amount" value={{item.price}}>
    <input type="hidden" name="virtual_account_id" value={{account.id}}>
    <input type="hidden" name="item_id" value={{item.id}}>
    <input type="submit" value="Payment made" class="submit">
  </form>
</div>
{% endblock content %}

app/templates/app/store.html
{% extends 'app/base.html' %}
{% load humanize %}
{% block content %}
<h1>Store</h1>
<dl>
  {% for item in items %}
    <dt>
      <a href="{% url 'app:pay' item.id item.currency %}">
        {{item.name}}
      </a>
      - {{item.price | intcomma}} {{item.currency}}
    </dt>
    <dd>
      {{item.description}}
    </dd>
  {% endfor %}
</dl>
<p>
  Go to 
  <a href="{% url 'app:orders' %}">Orders</a>
</p>
{% endblock content %}